server:
  port: 8701
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      url: jdbc:mysql://127.0.0.1:3306/dev?connectTimeout=20000&socketTimeout=20000&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
    slave:
      url: jdbc:mysql://127.0.0.1:3307/dev?connectTimeout=20000&socketTimeout=20000&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 123456

logging:
  path: D://DownLoad//Boot//logs
  config: classpath:spring-logback.xml